#!/bin/bash

: ${TAG:=rmd-renderer}
[ -z ${DOCKER_FILE} ]\
  && echo No Dockerfile set, skiping build..\
  || make tag=$TAG docker_file=$DOCKER_FILE

export DOCS=/docs
docker run -it -v $(pwd)/${1:-.}:$DOCS $TAG
